INSERT INTO `course` (`id`, `program`, `code`, `name`) VALUES
(1, 'BCA', 'BCS011', 'Computer Basics and PC Software'),
(2, 'BCA', 'BCS012', 'Mathematics'),
(3, 'BCA', 'BCS031', 'Programming in C++'),
(4, 'BCA', 'BCS040', 'Statistical Techniques'),
(5, 'BCA', 'BCS041', 'Fundamentals of Computer Networks'),
(6, 'BCA', 'BCS042', 'Introduction to Algorithm Design'),
(7, 'BCA', 'BCS051', 'Introduction to Software Engineering'),
(8, 'BCA', 'BCS052', 'Network Programming and Administration'),
(9, 'BCA', 'BCS053', 'Web Programming'),
(10, 'BCA', 'BCS054', 'Computer Oriented Numerical Techniques'),
(11, 'BCA', 'BCS055', 'Business Communication '),
(12, 'BCA', 'BCS062', 'ECommerce'),
(13, 'BCA', 'BCSL013', 'Computer Basics and PC Software Lab'),
(14, 'BCA', 'BCSL021', 'C Language Programming Lab'),
(15, 'BCA', 'BCSL022', 'Assembly Language Programming Lab'),
(16, 'BCA', 'BCSL032', 'C++ Programming Lab'),
(17, 'BCA', 'BCSL033', 'Data and File Structures Lab'),
(18, 'BCA', 'BCSL034', 'DBMS Lab'),
(19, 'BCA', 'BCSL043', 'Java Programming Lab'),
(20, 'BCA', 'BCSL044', 'Statistical Techniques Lab'),
(21, 'BCA', 'BCSL045', 'Algorithm Design Lab'),
(22, 'BCA', 'BCSL056', 'Network Programming and Administration Lab '),
(23, 'BCA', 'BCSL057', 'Web Programming Lab'),
(24, 'BCA', 'BCSL058', 'Computer Oriented Numerical Techniques Lab'),
(25, 'BCA', 'BCSL063', 'Operating System Concepts and Networking Management Lab'),
(26, 'BCA', 'BCSP064', 'Project'),
(27, 'BCA', 'ECO01', 'Business Organization'),
(28, 'BCA', 'ECO02', 'Accountancy1'),
(29, 'BCA', 'FEG02', 'Foundation course in English 2'),
(30, 'BCA', 'MCS011', 'Problem Solving and Programming'),
(31, 'BCA', 'MCS012', 'Computer Organization and Assembly Language Programming'),
(32, 'BCA', 'MCS013', 'Discrete Mathematics'),
(33, 'BCA', 'MCS014', 'Systems Analysis and Design'),
(34, 'BCA', 'MCS015', 'Communication Skills '),
(35, 'BCA', 'MCS021', 'Data and File Structures'),
(36, 'BCA', 'MCS022', 'Operating System Concepts and Networking Management'),
(37, 'BCA', 'MCS023', 'Introduction to Database Management Systems'),
(38, 'BCA', 'MCS024', 'Object Oriented Technologies and Java Programming'),
(39, 'BCA', 'MCSL016', 'Internet Concepts and Web Design'),
(40, 'MCA', 'MCS011', 'Problem Solving and Programming'),
(41, 'MCA', 'MCS012', 'Computer Organization and Assembly Language Programming'),
(42, 'MCA', 'MCS013', 'Discrete Mathematics'),
(43, 'MCA', 'MCS014', 'Systems Analysis and Design'),
(44, 'MCA', 'MCS015', 'Communication Skills '),
(45, 'MCA', 'MCSL016', 'Internet Concepts and Web Design'),
(46, 'MCA', 'MCSL017', 'C and Assembly Language Programming Lab'),
(47, 'MCA', 'MCS021', 'Data and File Structures'),
(48, 'MCA', 'MCS022', 'Operating System Concepts and Networking Management'),
(49, 'MCA', 'MCS023', 'Introduction to Database Management Systems'),
(50, 'MCA', 'MCS024', 'Object Oriented Technologies and Java Programming'),
(51, 'MCA', 'MCSL025', 'Lab (Based on MCS021, 022,023 & 024)'),
(52, 'MCA', 'MCS031', 'Design and Analysis of Algorithms'),
(53, 'MCA', 'MCS032', 'Object Oriented Analysis and Design	'),
(54, 'MCA', 'MCS033', 'Advanced Discrete Mathematics'),
(55, 'MCA', 'MCS034', 'Software Engineering'),
(56, 'MCA', 'MCS035', 'Accountancy and Financial Management'),
(57, 'MCA', 'MCSL036', 'Lab (based on MCS032, 034 and 035)'),
(58, 'MCA', 'MCS041', 'Operating Systems'),
(59, 'MCA', 'MCS042', 'Data Communication and Computer Networks'),
(60, 'MCA', 'MCS043', 'Advanced Database Management Systems'),
(61, 'MCA', 'MCS044', 'Mini Project'),
(63, 'MCA', 'MCSL045', 'Lab (UNIX & Oracle)'),
(64, 'MCA', 'MCS051', 'Advanced Internet Technologies'),
(65, 'MCA', 'MCS052', 'Principles of Management and Information System'),
(66, 'MCA', 'MCS053', 'Computer Graphics and Multimedia'),
(67, 'MCA', 'MCSL054', 'Lab (based on MCS051 & 053)'),
(68, 'MCA', 'MCSE003', 'Artificial Intelligence and Knowledge Management'),
(69, 'MCA', 'MCSE004', 'Numerical and Statistical Computing'),
(70, 'MCA', 'MCSE011', 'Parallel Computing'),
(71, 'MCA', 'MCSP060', 'Project\r\n'),
(72, 'BA', 'FEG01', 'Foundation Course in English1 Or Foundation Course in Hindi2'),
(73, 'BA', 'FST01', 'Foundation Course in Science and Technology'),
(74, 'BA', 'BHDF01', 'Foundation Course in Hindi'),
(75, 'BA', 'FHS1', 'Foundation Course in Humanities and Social Sciences'),
(76, 'BA', 'FGB01', 'Foundation Course in Bengali'),
(77, 'BA', 'FKD1', 'Foundation Course in Kannada'),
(78, 'BA', 'FML1', 'Foundation Course in Malayalam'),
(79, 'BA', 'FMT1', 'Foundation Course in Marathi'),
(80, 'BA', 'FOR1', 'Foundation Course in Oriya'),
(81, 'BA', 'FOR1', 'Foundation Course in Oriya'),
(82, 'BA', 'FPB1', 'Foundation Course in Punjabi'),
(83, 'BA', 'FTM1', 'Foundation Course in Tamil'),
(84, 'BA', 'FTG1', 'Foundation Course in Telugu'),
(85, 'BA', 'FUD1', 'Foundation Course in Urdu'),
(86, 'BA', 'BEGE101', 'From Language to Literature'),
(87, 'BA', 'EEG02', 'The Structure of Modern English'),
(88, 'BA', 'EEG03', 'Communication Skills in English'),
(89, 'BA', 'EEG04', 'English for Practical Purposes'),
(90, 'BA', 'EEG05', 'Understanding Prose'),
(91, 'BA', 'EEG06', 'Understanding Poetry'),
(92, 'BA', 'EEG06', 'Understanding Poetry'),
(93, 'BA', 'EEG07', 'Understanding Drama'),
(94, 'BA', 'EEG08', 'Reading the Novel'),
(95, 'BA', 'AFW(E)', 'Feature Writing'),
(96, 'BA', 'AWR(E)', 'Writing for Radio'),
(97, 'BA', 'AWR(H)', 'Radio Lekhan (Hindi)'),
(98, 'BA', 'EHD01', 'Hindi Gadya'),
(99, 'BA', 'EHD02', 'Hindi Kavya'),
(100, 'BA', 'EHD03', 'Hindi Sahitya ka Itihas evam Sahitya Parichay'),
(101, 'BA', 'EHD04', 'Madhyakaleen Bharatiya Sahitya: Samaj aur Sanskriti'),
(102, 'BA', 'EHD05', 'Adhunik Bharatiya Sahitya: Navjagaran aur Rashtriya Chetna'),
(103, 'BA', 'EHD06', 'Hindi Bhasha: Itihas aur Vartman'),
(104, 'BA', 'EHD07', 'Hindi Samrachna'),
(105, 'BA', 'CTE03', 'Teaching Strategies'),
(106, 'BA', 'CTE04', 'Teaching English (Elementary School)'),
(107, 'BA', 'CTE05', 'Teaching English (Secondary School)'),
(108, 'BA', 'FAS01', 'Foundation Course in Assamese'),
(109, 'BA', 'FEG1', 'Foundation Course in English1'),
(110, 'BA', 'AOM1', 'Office Organisation Management'),
(111, 'BA', 'ASP1', 'Secretarial Practice'),
(112, 'BA', 'AHE1', 'Human Environment'),
(113, 'BA', 'EHI1', 'Modern India, 18571964`'),
(114, 'BA', 'EHI2', 'India: Earliest Times to 8th Century A.D.'),
(115, 'BA', 'EHI3', 'India From 8th to 15th Century A.D.'),
(116, 'BA', 'EHI4', 'India From 16th to Mid 18th Century A.D.'),
(117, 'BA', 'ESO15', 'Society and Religion'),
(118, 'BA', 'BPVI028', 'Entrepreneurship and Marketing'),
(119, 'BA', 'DECE1', 'Organising Child Care Services'),
(120, 'BA', 'MPA012', 'Administrative Theory'),
(121, 'BA', 'AED1', 'Export Procedures and Documentation'),
(122, 'BA', 'ATR1', 'Translation'),
(123, 'BA', 'ACS1', 'Consumer Studies ACS1'),
(124, 'BA', 'BCOA001', 'Business Communication and Entrepreneurship'),
(125, 'BA', 'DNHE 01', 'Nutrition for the Community'),
(126, 'BA', 'MS51', 'Operations Research'),
(127, 'BA', 'EU1', 'History of Urdu Language'),
(128, 'BA', 'EU2', 'History of Urdu Literature'),
(129, 'BA', 'EU3', 'Urdu Poetry'),
(130, 'BA', 'EU4', 'Urdu Fiction'),
(131, 'BA', 'EU5', 'Urdu NonFictional Prose'),
(132, 'BA', 'EU6', 'Elements of Urdu Literature'),
(133, 'BA', 'EU7', 'Diasprestic Urdu Literature'),
(134, 'BA', 'EU8', 'Women in Urdu Literature'),
(135, 'BA', 'EU9', 'SocioCultural Forms in Urdu'),
(136, 'BA', 'EPS11', 'Political Ideas and Ideologies'),
(137, 'BA', 'EPS12', 'Government & Politics in India'),
(138, 'BA', 'EPS03', 'Modern Indian Political Thought'),
(139, 'BA', 'EPS15', 'South Asia: Economy, Society'),
(140, 'BA', 'EPS06', 'Government and Politics in East'),
(141, 'BA', 'EPS07', 'International Relations'),
(142, 'BA', 'EPS07', 'International Relations'),
(143, 'BA', 'EPS08', 'Government and Politics in Australia'),
(144, 'BA', 'EPS09', 'Comparative Government and Politics'),
(145, 'BA', 'EHI05', 'India from Mid 18th to Mid 19th Century'),
(146, 'BA', 'EHI06', 'History of China and Japan 18401949'),
(147, 'BA', 'EHI07', 'Modern Europe: Mid 18th to Mid 20th Century'),
(148, 'BA', 'BECE015', 'Elementary Mathematical Methods in Economic Development'),
(149, 'BA', 'BECE016', 'Economic Development: Comparative'),
(150, 'BA', 'EEC07', 'Industrial Development in In'),
(151, 'BA', 'EEC10', 'National Income Accounting'),
(152, 'BA', 'EEC11', 'Fundamentals of Economics'),
(153, 'BA', 'BECE002', 'Indian Economic Development:Issues and Perspectives'),
(154, 'BA', 'EEC13', 'Elementary Statistical Methods and Survey Techniques'),
(155, 'BA', 'EEC14', 'Agricultural Development in India'),
(156, 'BA', 'EPA3', 'Development Administration'),
(157, 'BA', 'EPA4', 'Personnel Administration'),
(158, 'BA', 'EPA5', 'Financial Administration'),
(159, 'BA', 'EPA6', 'Public Policy'),
(160, 'BA', 'APM1', 'Integrated Pest Management'),
(161, 'BA', 'AEC1', 'Environmental Chemistry'),
(162, 'BA', 'AST01', 'Statistical techniques'),
(163, 'BA', 'AMT1', 'Teaching of Primary School Mathematics'),
(164, 'BA', 'BHDA101', 'Samachar Lekhan aur Feature Lekhan'),
(165, 'BA', 'ESO11', 'The Study of Society'),
(166, 'BA', 'ESO12', 'Society in India'),
(167, 'BA', 'ESO13', 'Sociological Thought'),
(168, 'BA', 'ESO14', 'Society and Stratification'),
(169, 'BA', 'ESO16', 'Social Problems in India'),
(170, 'BA', 'BPY001', 'Indian Philosophy: Part I'),
(171, 'BA', 'BPY002', 'Logic: Classical and Symbolic'),
(172, 'BA', 'BPY003', 'Ancient and Medieval Philosophy'),
(173, 'BA', 'BPY004', 'Religions of the World'),
(174, 'BA', 'BPY005', 'Indian Philosophy: Part II'),
(175, 'BA', 'BPY006', 'Metaphysics'),
(176, 'BA', 'BPY007', 'Ethics'),
(177, 'BA', 'BPY008', 'Modern Western Philosophy'),
(178, 'BA', 'BPY009', 'Contemporary Western Philosophy'),
(179, 'BA', 'BPY010', 'Epistemology'),
(180, 'BA', 'BPY011', 'Philosophy of Human Persons'),
(181, 'BA', 'BPY012', 'Philosophy of Science and Cosmology'),
(182, 'BCOM', 'FEG02', 'Foundation Course in English'),
(183, 'BCOM', 'FST1', 'Foundation Course in Science and Technology'),
(184, 'BCOM', 'FEG1', 'Foundation Course in English1'),
(185, 'BCOM', 'FHD2', 'Foundation Course in Hindi2'),
(186, 'BCOM', 'FHD1', 'Foundation Course in Hindi1'),
(187, 'BCOM', 'MSW009', 'Community Organisation Management for Community Development'),
(188, 'BCOM', 'ECO1', 'Business Organisation'),
(189, 'BCOM', 'ECO02', 'AccountancyI'),
(190, 'BCOM', 'ECO03', 'Management Theory'),
(191, 'BCOM', 'ECO05', 'Mercantile Law'),
(192, 'BCOM', 'ECO06', 'Economic Theory'),
(193, 'BCOM', 'ECO07', 'Elements of Statistics'),
(194, 'BCOM', 'ECO08', 'Company Law'),
(195, 'BCOM', 'ECO09', 'Money, Banking and Financial Institutions'),
(196, 'BCOM', 'ECO10', 'Elements of Costing'),
(197, 'BCOM', 'ECO11', 'Elements of Income Tax'),
(198, 'BCOM', 'ECO12', 'Elements of Auditing'),
(199, 'BCOM', 'ECO13', 'Business Environment'),
(200, 'BCOM', 'ECO14', 'AccountancyII'),
(201, 'BCOM', 'AFW(E)', 'Feature Writing'),
(202, 'BCOM', 'AWR(E)', 'Writing for Radio'),
(203, 'BCOM', 'AWR(H)', 'Radio Lekhan (Hindi)'),
(204, 'BCOM', 'CTE03', 'Teaching Strategies'),
(205, 'BCOM', 'CTE04', 'Teaching English (Elementary School)'),
(206, 'BCOM', 'CTE05', 'Teaching English (Secondary School)'),
(207, 'BCOM', 'AOM1', 'Office Organisation Management'),
(208, 'BCOM', 'ASP1', 'Secretarial Practice'),
(209, 'BCOM', 'AHE1', 'Human Environment'),
(210, 'BCOM', 'AMT01', 'Teaching of Primary School Mathematics'),
(211, 'BCOM', 'AMK1', 'Marketing AMK1'),
(212, 'BCOM', 'AED1', 'Export Procedures and Documentation'),
(213, 'BCOM', 'ATR1', 'Translation'),
(214, 'BCOM', 'ACC1', 'Organizing Childcare Services'),
(215, 'BCOM', 'ANC1', 'Nutrition for the Community ANC1'),
(216, 'BCOM', 'ACS1', 'Consumer Studies ACS1'),
(217, 'MEG', 'MEG01', 'British Poetry'),
(218, 'MEG', 'MEG02', 'British Drama'),
(219, 'MEG', 'MEG03', 'British Novel'),
(220, 'MEG', 'MEG04', 'Aspects of Language'),
(221, 'MEG', 'MEG05', 'Literary Criticism and Theory'),
(222, 'MEG', 'MEG06', 'American Literature'),
(223, 'MEG', 'MEG07', 'Indian English Literature'),
(224, 'MEG', 'MEG08', 'New Literatures in English'),
(225, 'MEG', 'MEG09', 'Australian Literature'),
(226, 'MEG', 'MEG10', 'English Studies in India'),
(227, 'MEG', 'MEG11', 'American Novel'),
(228, 'MEG', 'MEG12', 'A Survey Course in 20th Century Canadian Literature'),
(229, 'MEG', 'MEG14', 'Contemporary Indian Literature in English Translation'),
(230, 'MEG', 'MEG15', 'Comparative Literature: Theory and Practice'),
(231, 'MEG', 'MEG16', 'Indian Folk Literature');